---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool-stage
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 10.5.73.0/24
  # Only allocate to Services labeled into this pool
  serviceSelector:
    matchExpressions:
      - key: lb.cilium.io/pool
        operator: In
        values: ["stage"]